### ISSUE TITLE
Support multiple input files

### ISSUE THREAD

**Issue by zeroZshadow** [silentorbit/protobuf#41]
Supporting *.proto as input instead of only single files will make this tool much easier to use.

**Comment by hultqvist** [comment]
It should already support that as far as it supports multiple .proto as arguments and it's usually the shell that expands the wildcard syntax rather than individual applications.

**Comment by zeroZshadow** [comment]
On windows, cmd, it does not allow this (while protoc does)

**Comment by hultqvist** [comment]
No flag for this feature, always on.

Let me know how it works
