### ISSUE TITLE
Have message classes use common Interface?

### ISSUE THREAD

**Issue by zeroZshadow** [silentorbit/protobuf#42]
Atm all messages use partial classes to get functions such as Serialize, but this makes it impossible to use something like a generic type constraint. Wouldn't it be preferable to have all Message classes implement a common Interface?

An example of why this would be usefull:

```
void SendMessage<T>(UInt32 messageType, T message) where T: IProtoMessage {
  using (MemoryStream stream = new MemoryStream()) {
      // Prefix header to actual message
      using (BinaryWriter writer = new BinaryWriter(stream)) {
        writer.Write(messageType);

        // Actual message
        T.Serialize(stream, message);
        websocket.Send(stream.ToArray());
      }
    }
}
```

As far as I know this isnt currently possible.

**Comment by hultqvist** [comment]
I don't see how the use of partial is a constraint, you can today write your own addition to a generated class like this.

    partial class Foo : IProtoMessage { }

And write your own IProtoMessage interface matching the current one for generated messages.

But I agree that the above could easily be integrated into the generator.

**Comment by hultqvist** [comment]
Although you could have a static Serialize of the interface the inner code in your example would look like this:

        // Actual message
        message.Serialize(stream);
        websocket.Send(stream.ToArray());

**Comment by zeroZshadow** [comment]
Yes i realized that interfaces cant have static functions (I'm still a little new to them)
It was just an example, the main issue is that dealing with serializing messages now takes a lot of duplicated code, or wierd workarounds.
