### ISSUE TITLE
It does support Field options

### ISSUE THREAD

**Issue by LazyPlanet** [silentorbit/protobuf#47]
**It shows in ProtoFeatures.proto:**

extend google.protobuf.FieldOptions {
  optional float my_field_option = 50002;
}

message MyMessage {
  optional int32 foo = 1 [(my_field_option) = 4.5];
}

**Excute:**

> CodeGenerator.exe --fix-nameclash ProtoFeatures.proto -o ./output

**Warning: Unknown field option: (my_field_option)**

It does support Field options as you say:
Field options:

access - default: public, can be any, even private if generating a local class(default)
codetype - set an int64 field type to "DateTime" or "TimeSpan", the serializer will do the conversion for you.
generate - if set to false(default: true), the field/property is expected to be defined elsewhere in the project rather than the generated code.
readonly - make the message field a c# readonly field rather than a property.

Thank you.

**Details:**
E:\PBNET\protobuf-master\TestProgram\ProtoSpec>CodeGenerator.exe --fix-nameclash ProtoFeatures.proto -o ./output
Parsing E:\PBNET\protobuf-master\TestProgram\ProtoSpec\ProtoFeatures.proto
Warning: Unknown option: (my_file_option) = Hello world!
Warning: Unknown option: (my_message_option) = 1234
Warning: Unknown field option: (my_field_option)
Parsing E:\PBNET\protobuf-master\TestProgram\ProtoSpec\google\protobuf\descriptor.proto
Warning: Unknown option: java_package = com.google.protobuf
Warning: Unknown option: java_outer_classname = DescriptorProtos
Warning: Unknown option: optimize_for = SPEED
ProtoCollection:
        message proto.test.my_message_v1
        message proto.test.my_message_v1_no_preserve
        message proto.test.my_message_v2
        message proto.test.their_message
        message proto.test.longMessage
        message proto.test.Data
        message proto.test.Container
        message proto.test.MyMessage
        message google.protobuf.FileDescriptorSet
        message google.protobuf.FileDescriptorProto
        message google.protobuf.DescriptorProto
        message google.protobuf.FieldDescriptorProto
        message google.protobuf.EnumDescriptorProto
        message google.protobuf.EnumValueDescriptorProto
        message google.protobuf.ServiceDescriptorProto
        message google.protobuf.MethodDescriptorProto
        message google.protobuf.FileOptions
        message google.protobuf.MessageOptions
        message google.protobuf.FieldOptions
        message google.protobuf.EnumOptions
        message google.protobuf.EnumValueOptions
        message google.protobuf.ServiceOptions
        message google.protobuf.MethodOptions
        message google.protobuf.UninterpretedOption
        message google.protobuf.SourceCodeInfo
Warning: renamed field: Google.Protobuf.DescriptorProto.ExtensionRangeField
Warning: renamed field: Google.Protobuf.UninterpretedOption.NamePart.NamePartField
Warning: renamed field: Google.Protobuf.SourceCodeInfo.LocationField
Saved: E:\PBNET\protobuf-master\TestProgram\ProtoSpec\output\ProtoFeatures.cs

**Comment by hultqvist** [comment]
The fields options "access", "generate"... are not the same type of field options as the protobuf field options. They are other type of options for fields used during code generation.

I'll have to look into the protobuf field options before I can see what they are supposed to do. Though I don't think this implementation supports much of them.

It's unclear what you need in your report.
The warnings should probably be addressed but actually implementing the feature might not have that high priority.
If you intend to use custom field options, what would your final use of it be?

**Comment by LazyPlanet** [comment]
As I am a mobile game programmer, I want to check value automatic using custom options...

Ex:
extend google.protobuf.FieldOptions {
optional int32  minValue = 50001;
optional int32  maxValue = 50002;
}

message MyMessage {
optional int32 rate = 1 [(minValue) = 0, (maxValue) = 100];
}

**Comment by hultqvist** [comment]
This would be a new feature.

I assume you would implement your own range check but would like to have the edge values in the generated c# code.

**Comment by LazyPlanet** [comment]
Yes...Thank u.
